org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
org.gradle.parallel=true
android.suppressUnsupportedCompileSdk=36
# Compatibility mode — fullMode breaks Zego Express JNI RegisterNatives
android.enableR8.fullMode=false
